### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by isurajmehra** [succkarz/instadp#2]
still not working brother, check its says "Username does not exist or server busy "

**Comment by succkarz** [comment]
Working fine on my local server as well as the free hosting server.

**Comment by isurajmehra** [comment]
![captafsfure](https://user-images.githubusercontent.com/22742900/43655695-5692302a-976d-11e8-9363-f0b5e1f42f34.JPG)
check this bro

**Comment by isurajmehra** [comment]
i think,, data.php file has error, please bro help me

**Comment by succkarz** [comment]
![Screen](https://user-images.githubusercontent.com/22551433/43662738-81a21fca-9784-11e8-8cf0-5e9980c33ab9.png)
Try with the latest master branch.

**Comment by isurajmehra** [comment]
Yes bro.i download latest master.. and installed it in.. https://saibabaspeaks.com/instadp-master  you can check this

**Comment by isurajmehra** [comment]
Brother can you send me.your zip file to my email please 🙏 koharg123@gmail.com

**Comment by succkarz** [comment]
You are using your fork master zip. Use this https://github.com/succkarz/instadp/archive/master.zip
